import { cpSync, readFileSync, writeFileSync, mkdirSync, rmSync, lstatSync, existsSync } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(root, 'src');
const outputDir = path.resolve(root, 'dist');
const read = file => readFileSync(path.join(root, file), 'utf8');
const readSource = file => readFileSync(path.join(sourceDir, file), 'utf8');
const write = (file, text) => writeFileSync(path.join(outputDir, file), text);
const { version } = JSON.parse(read('package.json'));

vm.runInThisContext(readSource('core.js'));
const core = globalThis.StreamGuardCore;

const MAX_PER_SET = 25000;
const MAX_TOTAL = 250000;
const LISTS = ['easylist', 'easyprivacy', 'adguard-base', 'adlibere-extra'];
const listSources = LISTS.map(id => read(`lists/${id}.txt`));

// Packaged rules use block/allow; dynamic rules provide local redirects.
const converted = [];
for (const source of listSources) converted.push(...core.filterRules(source.split(/\r?\n/)));
const seen = new Set();
const rules = [];
for (const rule of converted) {
  const c = rule.condition;
  const key = [
    rule.action.type,
    c.urlFilter,
    (c.resourceTypes || []).join(','),
    (c.initiatorDomains || []).join(','),
    (c.excludedInitiatorDomains || []).join(','),
  ].join('|');
  if (seen.has(key)) continue;
  seen.add(key);
  rules.push(rule.action.type === 'redirect' ? { ...rule, action: { type: 'block' } } : rule);
}
rules.length = Math.min(rules.length, MAX_TOTAL);

// Clear only this project's output directory, never a linked directory.
if (path.dirname(outputDir) !== root || path.basename(outputDir) !== 'dist') throw new Error('Invalid build output path.');
if (existsSync(outputDir) && lstatSync(outputDir).isSymbolicLink()) throw new Error('dist must not be a symlink.');
rmSync(outputDir, { recursive: true, force: true });
mkdirSync(path.join(outputDir, 'rulesets'), { recursive: true });
for (const file of ['background.js', 'core.js', 'catalog.js', 'options.html', 'options.js', 'options.css', 'icons', 'resources']) {
  cpSync(path.join(sourceDir, file), path.join(outputDir, file), { recursive: true });
}
const sets = [];
for (let start = 0; start < rules.length; start += MAX_PER_SET) {
  const chunk = rules.slice(start, start + MAX_PER_SET).map((rule, index) => ({ ...rule, id: index + 1 }));
  sets.push({ id: `ruleset-${sets.length + 1}`, path: `rulesets/ruleset-${sets.length + 1}.json`, count: chunk.length });
  write(sets[sets.length - 1].path, JSON.stringify(chunk));
}

const info = {
  version,
  generatedAt: new Date().toISOString(),
  staticRuleCount: rules.length,
  listRuleCount: converted.length,
  rulesetIds: sets.map(set => set.id),
  rulesets: sets,
};
const buildInfo = `/* Generated by tools/build.mjs. */\nglobalThis.StreamGuardBuild = ${JSON.stringify(info)};\n`;
write('build-info.js', buildInfo);

const popups = { block: { host: [], any: [] }, allow: { host: [], any: [] } };
for (const source of listSources) {
  for (const line of source.split(/\r?\n/)) {
    const pattern = core.popupPattern(line);
    if (!pattern) continue;
    const bucket = popups[pattern.allow ? 'allow' : 'block'][pattern.kind];
    if (!bucket.includes(pattern.value)) bucket.push(pattern.value);
  }
}
popups.block.host = popups.block.host.filter(value => !popups.allow.host.includes(value));
const popupPatterns = `/* Generated by tools/build.mjs from $popup rules. */\nglobalThis.StreamGuardPopups = ${JSON.stringify(popups)};\n`;
write('popup-patterns.js', popupPatterns);

const shared = readSource('core.js') + readSource('catalog.js') + buildInfo;
write('main.bundle.js', shared + popupPatterns + readSource('main.js'));
write('content.bundle.js', shared + readSource('content.js'));

const manifest = JSON.parse(readSource('manifest.json'));
manifest.version = version;
manifest.declarative_net_request.rule_resources = sets.map(set => ({ id: set.id, enabled: true, path: set.path }));
write('manifest.json', `${JSON.stringify(manifest, null, 2)}\n`);

console.log(`Built adLibere ${version} in dist/`);
console.log(`${rules.length} static rules across ${sets.length} rulesets`);
console.log(`${popups.block.host.length} popup hosts and ${popups.block.any.length} URL patterns`);
